# Generated by Django 2.1.7 on 2019-03-01 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='dob',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='day of birth'),
        ),
        migrations.AddField(
            model_name='kin',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kin',
            name='mob',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month of birth'),
        ),
        migrations.AddField(
            model_name='kin',
            name='yob',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2019)], verbose_name='year of birth'),
        ),
    ]
