# Generated by Django 2.1.7 on 2019-03-01 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20190301_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='dod',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='day of death'),
        ),
        migrations.AddField(
            model_name='kin',
            name='mod',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month of death'),
        ),
        migrations.AddField(
            model_name='kin',
            name='yod',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2019)], verbose_name='year of death'),
        ),
    ]
