# Generated by Django 2.1.7 on 2019-03-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20190301_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kin',
            options={'default_related_name': 'kin', 'get_latest_by': ['yob', 'mob', 'dob'], 'ordering': ['-yob', '-mob', '-dob'], 'verbose_name_plural': 'kin'},
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='is_deceased',
            new_name='deceased',
        ),
    ]
